name: Build and Test Xen

on:
  pull_request:
    branches: [ develop ]

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install coreutils \
        build-essential gcc git make flex bison \
        software-properties-common libwww-perl python \
        bin86 gdb bcc liblzma-dev python-dev gettext iasl \
        uuid-dev libncurses5-dev libncursesw5-dev pkg-config \
        libgtk2.0-dev libyajl-dev sudo \
        time

    - uses: actions/checkout@v1

    - name: build CBMC tools
      run: make -C src minisat2-download
      run: make -C src cbmc.dir goto-cc.dir goto-diff.dir

    - name: get one-line-scan
      run: git clone https://github.com/awslabs/one-line-scan.git

    - name: get Xen 4.13
      run: git clone git://xenbits.xen.org/xen.git xen_4_13 && cd xen_4_13 && git reset --hard RELEASE-4.13.0

    - name: compile Xen with CBMC via one-line-scan
      run: ls
      run: pwd
      run: ls src/*
      run: ln -sf src/goto-cc/goto-cc src/goto-cc/goto-ld
      run: ln -sf src/goto-cc/goto-cc src/goto-cc/goto-as
      run: ln -sf src/goto-cc/goto-cc src/goto-cc/goto-g++
      run: PATH=$PATH:src/cbmc:src/goto-cc one-line-scan/one-line-scan --no-analysis --trunc-existing --extra-cflags -Wno-error -o CPROVER -j 3 -- make -C xen xen -j $(nproc) -k 
