name: Build and Test Xen

on:
  pull_request:
    branches: [ develop ]

jobs:
  CompileXen:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Packages
        env:
          # This is needed in addition to -yq to prevent apt-get from asking for
          # user input
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y coreutils  build-essential gcc git make flex bison software-properties-common libwww-perl python
          sudo apt-get install -y bin86 gdb bcc liblzma-dev python-dev gettext iasl uuid-dev libncurses5-dev libncursesw5-dev pkg-config
          sudo apt-get install -y libgtk2.0-dev libyajl-dev sudo time
      - name: build CBMC tools
        run: |
          make -C src minisat2-download
          make -C src cbmc.dir goto-cc.dir goto-diff.dir
      - name: get one-line-scan
        run: git clone -b path-addition https://github.com/awslabs/one-line-scan.git
      - name: get Xen 4.13
        run: git clone git://xenbits.xen.org/xen.git xen_4_13 && cd xen_4_13 && git reset --hard RELEASE-4.13.0
      - name: compile Xen with CBMC via one-line-scan
        run: |
          ls
          pwd
          ls src/goto-cc/goto-cc
          ln -s src/goto-cc/goto-cc src/goto-cc/goto-ld
          ln -s src/goto-cc/goto-cc src/goto-cc/goto-as
          ln -s src/goto-cc/goto-cc src/goto-cc/goto-g++
          one-line-scan/one-line-scan --add-to-path src/cbmc --add-to-path src/goto-cc --no-analysis --trunc-existing --extra-cflags -Wno-error -o CPROVER -j 3 -- env
          one-line-scan/one-line-scan --add-to-path src/cbmc --add-to-path src/goto-cc --no-analysis --trunc-existing --extra-cflags -Wno-error -o CPROVER -j 3 -- make -C xen xen -j $(nproc) -k 
